

<div id="content">
	<div class="jumbotron">
	   <form id="login" action="#" method="POST">
	   	<img id="secure_login" src="<?php echo $this->basePath('img/user_login.png') ?>" height="32" width="32"/>
	        <input type="email" placeholder="Please enter your email"/>
	        	<br>
	        <input type="password" placeholder="Password"/>
	        	<br>
	        <button name="login">Login</button>
	    </form>
	</div>
</div>


