<div id="product_page">
	<div id="wrapper">
		<div id="tab">
			<span>
				<nav>
					<ul>
						<li>
							<a id="upload" href="#"> Upload Products</a>
						</li>
						<li>
							<a id="push" href="#"> Push Products Live</a>
						</li>
						<li>
							<a id="extract" href="#"> Extract Products</a>
						</li>
					</ul>
				</nav>
			</span>
		</div>
		<div id="content">
			<div id="upload">
				<form method="post" action="#" id="upload">
					<select id="select">
						<option value="SunGlasses">
							Sun Glasses
						</option>
						<option value="Glasses">
							Glasses
						</option>
						<option value="ContactLenses">
							Contact Lenses
						</option>
					</select>
					<br>
					<input type="file" name="file">
					<br>
					<button name="upload">Upload</button>
				</form>
			</div>
			<div id="push">
				<span>
					<p>
						<h3>
							Verify and push to live
						</h3>
					</p>
				</span>
				<button>Push to Live</button>
				<button>Push to Live</button>
				<table>
					<thead>
						<th></th>
						<th></th>
						<th></th>
						<th></th>
						<th></th>
						<th></th>
						<th></th>
					</thead>
					<tbody>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
					</tbody>
				</table>
			</div>
			<div id="extract">
			</div>
		</div>
	</div>

</div>